<?php
 $classname[1][1]="肉干肉脯/豆干/熟食";
    $classname[1][2]="膨化食品";
    $classname[1][3]="鱿鱼丝/鱼干/海味即食";
    $classname[2][1]="饼干";
    $classname[2][2]="威化";
    $classname[2][3]="传统糕点";
    $classname[2][4]="西式糕点";
    $classname[3][1]="纯牛奶";
    $classname[3][2]="酸奶";
    $classname[3][3]="豆奶";
    $classname[4][1]="巧克力";
    $classname[4][2]="糖果零食";
    $classname[5][1]="水";
    $classname[5][2]="果汁";
    $classname[5][3]="碳酸饮料";
    $classname[5][4]="功能饮料";
    $classname[5][5]="乳品";
    $classname[6][1]="速溶咖啡";
    $classname[6][2]="咖啡豆";
    $classname[6][3]="咖啡伴侣";
    $classname[7][1]="调味料";
    $classname[7][2]="调味油";
    $classname[7][3]="料酒";
    $classname[8][1]="方便面";
    $classname[8][2]="罐头";
    $classname[8][3]="火腿肠";
    $classname[8][4]="其他速食";
    $classname[9][1]="食用油";
    $classname[9][2]="米类";
    $classname[9][3]="粉丝";
    $classname[9][4]="干货";
    $classname[10][1]="传统滋补";
    $classname[10][2]="西洋滋补";
    
    ?>

